### PR TITLE
Always set unix file separators, as command is run in container. Fixes #33

### LINKED ISSUE #33: AutoCleanReports does not work when running on windows environment
Reports are not cleaned up after running test on Windows. 
It seems this is because CypressContainer.java are using native unix commands for removing files. 
https://github.com/wimdeblauwe/testcontainers-cypress/blob/ac49b5850b48173be9b34a3a749ae7ea142f5ad2/src/main/java/io/github/wimdeblauwe/testcontainers/cypress/CypressContainer.java#L290
`        if (autoCleanReports) {
            String reportsPathInContainer = getReportsPathInContainer();
            if (reportsPathInContainer.equals("/")) {
                throw new IllegalArgumentException("Reports path was /, not allowing to delete everything");
            }
            LOGGER.debug("Removing reports from {}", reportsPathInContainer);
            builder.append("rm -rf ")
                   .append(reportsPathInContainer)
                   .append(" && ");
        }
`

### PR DESCRIPTION
**Pull request by Halstor**

### CODE REVIEW

**Comment by wimdeblauwe** [comment]
How sure are you that `separatorsToSystem` is no longer needed? It was added in commit https://github.com/wimdeblauwe/testcontainers-cypress/commit/c2c2b3f7a9a5321b38a4b2283441be4603ff2dc5 to ensure things are working on Windows and it was confirmed to have been fixed on Windows (See https://github.com/wimdeblauwe/testcontainers-cypress/issues/17#issuecomment-675716601 - I don't have Windows to test).

**Comment by wimdeblauwe** [comment]
Thanks for the update. What version of Cypress are you using? If I merge this now and do a release, it will be with Cypress 9.1.0. Is this ok, or would you like a release with an older version of Cypress ?

**Comment by Halstor** [comment]
I have looked in to this, and initial I tested this with JDK 11. After your concern I have also tested this with JDK 8, and it seems to be necessery to have this if you are using JDK 8. I have re-introduced separatorsToSystem to support Java 8

From what I can understand Path.startsWith(...) will handle this if you are using Java 9+ as from this release the `startsWith` method handles the conversion based on the filesytem: 
`default boolean startsWith(String other) {
        return startsWith(getFileSystem().getPath(other));
    }`

**Comment by Halstor** [comment]
> 

Cypress 9.1.0 works fine.

**Comment by wimdeblauwe** [comment]
Thank you for your PR. Version 1.6.1 is now released.

**Pull request merged**
